version: "3"
services:
  api:
    build: api/
    depends_on:
      - db
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
  web:
    build: www/
    depends_on:
      - api
  db:
    image: postgres
    volumes:
      - db_store:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
volumes:
  db_store:
